import { mkdir, rm, writeFile } from "fs/promises";
import path from "path";

import type { FirstbaseAnswers } from "./types";

function frameworkLabel(answers: FirstbaseAnswers): string {
  return answers.framework === "next" ? "Next.js" : "React + Vite";
}

function enabledModules(answers: FirstbaseAnswers): string[] {
  return [
    answers.reactQuery ? "React Query" : "",
    answers.auth ? "Auth scaffold" : "",
    answers.forms ? "Forms stack" : "",
    answers.toasts ? "Toast system" : "",
    answers.i18n ? "i18n" : "",
    answers.seo ? "SEO metadata" : "",
    answers.tests ? "Vitest setup" : "",
  ].filter(Boolean);
}

async function write(projectPath: string, relativePath: string, content: string): Promise<void> {
  const filePath = path.join(projectPath, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
}

function packageJson(answers: FirstbaseAnswers): string {
  const scripts: Record<string, string> = {
    dev: answers.framework === "next" ? "next dev" : "vite",
    build: answers.framework === "next" ? "next build" : "vite build",
    format: "prettier . --write",
    "format:check": "prettier . --check",
    check: answers.tests
      ? "npm run format:check && npm run test && npm run build"
      : "npm run format:check && npm run build",
  };

  if (answers.framework === "next") {
    scripts.start = "next start";
    scripts.lint = "eslint .";
  }

  if (answers.tests) {
    scripts.test = "vitest --run";
    scripts["test:watch"] = "vitest";
  }

  const dependencies: Record<string, string> = {
    "@vitejs/plugin-react": answers.framework === "react" ? "6.0.1" : (undefined as never),
    next: answers.framework === "next" ? "16.2.4" : (undefined as never),
    react: "19.2.5",
    "react-dom": "19.2.5",
    axios: "1.15.0",
    "lucide-react":
      answers.framework === "next" || answers.uiLibrary === "shadcn"
        ? "1.8.0"
        : (undefined as never),
    "@tanstack/react-query": answers.reactQuery ? "5.99.0" : (undefined as never),
    "react-hook-form": answers.forms ? "7.72.1" : (undefined as never),
    zod: answers.forms ? "4.3.6" : (undefined as never),
    "@hookform/resolvers": answers.forms ? "5.2.2" : (undefined as never),
    sonner: answers.toasts ? "2.0.7" : (undefined as never),
    clsx: answers.uiLibrary === "shadcn" ? "2.1.1" : (undefined as never),
    "tailwind-merge": answers.uiLibrary === "shadcn" ? "3.5.0" : (undefined as never),
    "class-variance-authority": answers.uiLibrary === "shadcn" ? "0.7.1" : (undefined as never),
  };

  const devDependencies: Record<string, string> = {
    typescript: answers.language === "ts" ? "5.9.3" : (undefined as never),
    tailwindcss: "3.4.17",
    postcss: "8.5.10",
    autoprefixer: "10.4.21",
    prettier: "3.8.3",
    eslint: answers.framework === "next" ? "10.2.1" : (undefined as never),
    "eslint-config-next": answers.framework === "next" ? "16.2.4" : (undefined as never),
    vitest: answers.tests ? "4.1.4" : (undefined as never),
    jsdom: answers.tests ? "29.0.2" : (undefined as never),
    "@testing-library/react": answers.tests ? "16.3.2" : (undefined as never),
    "@testing-library/jest-dom": answers.tests ? "6.9.1" : (undefined as never),
    husky: answers.setupHusky ? "9.1.7" : (undefined as never),
  };

  function compact(record: Record<string, string>): Record<string, string> {
    return Object.fromEntries(
      Object.entries(record).filter(([, value]) => typeof value === "string"),
    );
  }

  return `${JSON.stringify(
    {
      name: answers.projectName,
      version: "0.1.0",
      private: true,
      scripts,
      dependencies: compact(dependencies),
      devDependencies: compact(devDependencies),
      engines: { node: ">=20.19.0" },
    },
    null,
    2,
  )}
`;
}

function readme(answers: FirstbaseAnswers): string {
  const modules = enabledModules(answers);

  return `# ${answers.projectName}

Generated by Firstbase Web for \`${frameworkLabel(answers)}\`.

## Stack

- Framework: ${frameworkLabel(answers)}
- Language: ${answers.language === "ts" ? "TypeScript" : "JavaScript"}
- Routing: ${answers.framework === "next" ? (answers.routing === "app" ? "App Router" : "Pages Router") : "N/A"}
- UI library: ${answers.uiLibrary === "shadcn" ? "shadcn/ui-compatible primitives" : "None"}
- Husky: ${answers.setupHusky ? "Enabled" : "Disabled"}
- Advanced modules: ${modules.length ? modules.join(", ") : "None"}

## Start

\`\`\`bash
npm install
npm run dev
\`\`\`

## Quality Gate

\`\`\`bash
npm run check
\`\`\`

This ZIP intentionally excludes \`node_modules\`.
`;
}

function docs(answers: FirstbaseAnswers): string {
  return `# Production Setup

This project was generated from the Firstbase website backend.

## Generation Answers

\`\`\`json
${JSON.stringify(answers, null, 2)}
\`\`\`

## Export Notes

- The archive excludes \`node_modules\`.
- The repository push flow should use a short-lived GitHub token.
- Re-run \`npm install\` after extracting the ZIP.
`;
}

function appSource(answers: FirstbaseAnswers): string {
  const title = `${answers.projectName} is ready`;
  const modules = enabledModules(answers);

  return `export default function Page() {
  return (
    <main className="min-h-screen bg-zinc-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-4xl">
        <p className="font-mono text-sm text-cyan-300">Generated by Firstbase</p>
        <h1 className="mt-4 text-5xl font-semibold">${title}</h1>
        <p className="mt-5 max-w-2xl text-zinc-300">
          ${frameworkLabel(answers)} foundation with Tailwind, API structure, documentation, and selected modules.
        </p>
        <div className="mt-8 grid gap-3 sm:grid-cols-2">
          ${["Tailwind baseline", "API client", "Production docs", ...modules]
            .map(
              (item) =>
                `<div className="rounded-xl border border-white/10 bg-white/5 p-4">${item}</div>`,
            )
            .join("\n          ")}
        </div>
      </section>
    </main>
  );
}
`;
}

function viteSource(answers: FirstbaseAnswers): string {
  return `import "./index.css";

export function App() {
  return (
    <main className="min-h-screen bg-zinc-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-4xl">
        <p className="font-mono text-sm text-cyan-300">Generated by Firstbase</p>
        <h1 className="mt-4 text-5xl font-semibold">${answers.projectName} is ready</h1>
        <p className="mt-5 max-w-2xl text-zinc-300">
          React + Vite foundation with Tailwind, API structure, documentation, and selected modules.
        </p>
      </section>
    </main>
  );
}
`;
}

export async function writeGeneratedProject(
  projectPath: string,
  answers: FirstbaseAnswers,
): Promise<void> {
  await rm(projectPath, { recursive: true, force: true });
  await mkdir(projectPath, { recursive: true });

  await write(projectPath, "package.json", packageJson(answers));
  await write(projectPath, "README.md", readme(answers));
  await write(projectPath, "docs/production-setup.md", docs(answers));
  await write(projectPath, ".gitignore", "node_modules\n.next\ndist\nbuild\n.env\n.env.local\n");
  await write(projectPath, ".env.example", "NEXT_PUBLIC_API_URL=https://api.example.com\n");
  await write(
    projectPath,
    "tailwind.config.ts",
    `export default { content: ["./**/*.{ts,tsx,js,jsx}"], theme: { extend: {} }, plugins: [] };\n`,
  );
  await write(
    projectPath,
    "postcss.config.cjs",
    `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };\n`,
  );
  await write(
    projectPath,
    answers.language === "ts" ? "lib/api.ts" : "lib/api.js",
    `import axios from "axios";\n\nexport const api = axios.create({ baseURL: process.env.NEXT_PUBLIC_API_URL, timeout: 15000 });\n`,
  );

  if (answers.framework === "next") {
    await write(
      projectPath,
      answers.language === "ts" ? "app/page.tsx" : "app/page.jsx",
      appSource(answers),
    );
    await write(
      projectPath,
      "app/globals.css",
      "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
    );
    await write(
      projectPath,
      answers.language === "ts" ? "app/layout.tsx" : "app/layout.jsx",
      answers.language === "ts"
        ? `import "./globals.css";\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`
        : `import "./globals.css";\n\nexport default function RootLayout({ children }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
    );
    return;
  }

  const mainFile = answers.language === "ts" ? "main.tsx" : "main.jsx";
  await write(
    projectPath,
    "index.html",
    `<div id="root"></div><script type="module" src="/src/${mainFile}"></script>\n`,
  );
  await write(
    projectPath,
    answers.language === "ts" ? "src/App.tsx" : "src/App.jsx",
    viteSource(answers),
  );
  await write(
    projectPath,
    `src/${mainFile}`,
    answers.language === "ts"
      ? `import { createRoot } from "react-dom/client";\nimport { App } from "./App";\n\ncreateRoot(document.getElementById("root")!).render(<App />);\n`
      : `import { createRoot } from "react-dom/client";\nimport { App } from "./App";\n\ncreateRoot(document.getElementById("root")).render(<App />);\n`,
  );
  await write(
    projectPath,
    "src/index.css",
    "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
  );
}
